Traceback (most recent call last):
  File "C:\Users\silve\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\silve\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\silve\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\silve\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\silve\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\silve\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\silve\AppData\Roaming\jupyterlab-desktop\jlab_server\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.boxplot(ypoints, color = 'skyblue') 

plt.title('Boxplot')
plt.ylabel('Y')

plt.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[10], line 1[0m
[1;32m----> 1[0m [43mplt[49m[38;5;241;43m.[39;49m[43mboxplot[49m[43m([49m[43mypoints[49m[43m,[49m[43m [49m[43mcolor[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mskyblue[39;49m[38;5;124;43m'[39;49m[43m)[49m 
[0;32m      3[0m plt[38;5;241m.[39mtitle([38;5;124m'[39m[38;5;124mBoxplot[39m[38;5;124m'[39m)
[0;32m      4[0m plt[38;5;241m.[39mylabel([38;5;124m'[39m[38;5;124mY[39m[38;5;124m'[39m)

[1;31mTypeError[0m: boxplot() got an unexpected keyword argument 'color'

